gText_Birch_Welcome::
	.string "Hello there! It's so very nice to\n"
	.string "meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is ROWAN.\p"
	.string "However, everyone just calls me the\n"
	.string "POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans live alongside POKéMON\n"
	.string "as friends.\p"
	.string "At times we play together, and at\n"
	.string "other times we work together.\p"
	.string "Some people use their POKéMON to\n"
	.string "battle and develop closer bonds\l"
	.string "with them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may\n"
	.string "learn more about POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, why don't you tell me a little\n"
	.string "bit about yourself?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_ConfirmGenderMale::
	.string "All right, so you're a boy?$"

gText_Birch_ConfirmGenderFemale::
	.string "All right, so you're a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_WhatsHisName::
	.string "What might his name be?$"

gText_Birch_SoItsRivalName::
	.string "{RIVAL}, is it?\p"
	.string "That's your friend's name?$"

gText_Birch_YourePlayer::
	.string "OK…\n"
	.string "so you're {PLAYER}{KUN}?\p"
	.string "A fine name that is!\p"
	.string "Now, this boy here…\n"
	.string "I believe he's your friend.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}{KUN}, the time has\n"
	.string "come.\p"
	.string "Your very own tale of grand adventure\n"
	.string "is about to unfold.\p"
	.string "On your journey you will meet\n"
	.string "countless POKéMON.\p"
	.string "I'm sure that along the way you will\n"
	.string "discover many things, perhaps even\l"
	.string "something about yourself.\p"
	.string "Now, go on, leap into the world of\n"
	.string "POKéMON!\p"
	.string "$"
