OreburghCity_OreburghMine_MapScripts::
	.byte 0

OreburghCity_OreburghMine_EventScript_NPC1::
	msgbox OreburghCity_OreburghMine_Text_NPC1, MSGBOX_NPC
	end

OreburghCity_OreburghMine_EventScript_NPC2::
	msgbox OreburghCity_OreburghMine_Text_NPC2, MSGBOX_NPC
	end

OreburghCity_OreburghMine_Text_NPC1:
	.string "OREBURGH MINE NPC 1$"

OreburghCity_OreburghMine_Text_NPC2:
	.string "OREBURGH MINE NPC 2$"
