JubilifeCity_Condominium_1F_MapScripts::
	.byte 0

JubilifeCity_Condominium_1F_EventScript_NPC1::
	msgbox JubilifeCity_Condominium_1F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC2::
	msgbox JubilifeCity_Condominium_1F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC3::
	msgbox JubilifeCity_Condominium_1F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC4::
	msgbox JubilifeCity_Condominium_1F_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC5::
	msgbox JubilifeCity_Condominium_1F_Text_NPC5, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC6::
	msgbox JubilifeCity_Condominium_1F_Text_NPC6, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_EventScript_NPC7::
	msgbox JubilifeCity_Condominium_1F_Text_NPC7, MSGBOX_NPC
	end

JubilifeCity_Condominium_1F_Text_NPC1:
	.string "CONDOMINIUM 1F NPC 1$"

JubilifeCity_Condominium_1F_Text_NPC2:
	.string "CONDOMINIUM 1F NPC 2$"

JubilifeCity_Condominium_1F_Text_NPC3:
	.string "CONDOMINIUM 1F NPC 3$"

JubilifeCity_Condominium_1F_Text_NPC4:
	.string "CONDOMINIUM 1F NPC 4$"

JubilifeCity_Condominium_1F_Text_NPC5:
	.string "CONDOMINIUM 1F NPC 5$"

JubilifeCity_Condominium_1F_Text_NPC6:
	.string "CONDOMINIUM 1F NPC 6$"

JubilifeCity_Condominium_1F_Text_NPC7:
	.string "CONDOMINIUM 1F NPC 7$"

JubilifeCity_Condominium_1F_EventScript_Sign1::
	msgbox JubilifeCity_Condominium_1F_Text_Sign1, MSGBOX_SIGN
	end

JubilifeCity_Condominium_1F_Text_Sign1:
	.string "CONDOMINIUM 1F SIGN 1$"
