JubilifeCity_DexNavCompany_3F_MapScripts::
	.byte 0

JubilifeCity_DexNavCompany_3F_EventScript_NPC1::
	msgbox JubilifeCity_DexNavCompany_3F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_3F_EventScript_NPC2::
	msgbox JubilifeCity_DexNavCompany_3F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_3F_EventScript_NPC3::
	msgbox JubilifeCity_DexNavCompany_3F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_3F_EventScript_Sign1::
	msgbox JubilifeCity_DexNavCompany_3F_Text_Sign1, MSGBOX_SIGN
	end

JubilifeCity_DexNavCompany_3F_EventScript_Sign2::
	msgbox JubilifeCity_DexNavCompany_3F_Text_Sign2, MSGBOX_SIGN
	end

JubilifeCity_DexNavCompany_3F_Text_NPC1:
	.string "DEX NAV COMPANY 3F NPC 1$"

JubilifeCity_DexNavCompany_3F_Text_NPC2:
	.string "DEX NAV COMPANY 3F NPC 2$"

JubilifeCity_DexNavCompany_3F_Text_NPC3:
	.string "DEX NAV COMPANY 3F NPC 3$"

JubilifeCity_DexNavCompany_3F_Text_Sign1:
	.string "DEX NAV COMPANY 3F SIGN 1$"

JubilifeCity_DexNavCompany_3F_Text_Sign2:
	.string "DEX NAV COMPANY 3F SIGN 2$"
