SandgemTown_ProfessorRowansLab_MapScripts::
	.byte 0

SandgemTown_ProfessorRowansLab_EventScript_NPC1::
	msgbox SandgemTown_ProfessorRowansLab_Text_NPC1, MSGBOX_NPC
	end

SandgemTown_ProfessorRowansLab_EventScript_NPC2::
	msgbox SandgemTown_ProfessorRowansLab_Text_NPC2, MSGBOX_NPC
	end

SandgemTown_ProfessorRowansLab_EventScript_NPC3::
	msgbox SandgemTown_ProfessorRowansLab_Text_NPC3, MSGBOX_NPC
	end

SandgemTown_ProfessorRowansLab_Text_NPC1:
	.string "PROFESSOR ROWANS LAB NPC 1$"

SandgemTown_ProfessorRowansLab_Text_NPC2:
	.string "PROFESSOR ROWANS LAB NPC 2$"

SandgemTown_ProfessorRowansLab_Text_NPC3:
	.string "PROFESSOR ROWANS LAB NPC 3$"
