OreburghCity_RightOfGymHouse_MapScripts::
	.byte 0

OreburghCity_RightOfGymHouse_EventScript_NPC1::
	msgbox OreburghCity_RightOfGymHouse_Text_NPC1, MSGBOX_NPC
	end

OreburghCity_RightOfGymHouse_EventScript_NPC2::
	msgbox OreburghCity_RightOfGymHouse_Text_NPC2, MSGBOX_NPC
	end

OreburghCity_RightOfGymHouse_Text_NPC1:
	.string "OREBURGH CITY RIGHT OF GYM HOUSE\n"
	.string "NPC 1$"

OreburghCity_RightOfGymHouse_Text_NPC2:
	.string "OREBURGH CITY RIGHT OF GYM HOUSE\n"
	.string "NPC 2$"
