JubilifeCity_TVStation_1F_MapScripts::
	.byte 0

JubilifeCity_TVStation_1F_EventScript_NPC1::
	msgbox JubilifeCity_TVStation_1F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_EventScript_NPC2::
	msgbox JubilifeCity_TVStation_1F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_EventScript_NPC3::
	msgbox JubilifeCity_TVStation_1F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_EventScript_NPC4::
	msgbox JubilifeCity_TVStation_1F_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_EventScript_NPC5::
	msgbox JubilifeCity_TVStation_1F_Text_NPC5, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_EventScript_NPC6::
	msgbox JubilifeCity_TVStation_1F_Text_NPC6, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_Text_NPC1:
	.string "TV STATION 1F NPC 1$"

JubilifeCity_TVStation_1F_Text_NPC2:
	.string "TV STATION 1F NPC 2$"

JubilifeCity_TVStation_1F_Text_NPC3:
	.string "TV STATION 1F NPC 3$"

JubilifeCity_TVStation_1F_Text_NPC4:
	.string "TV STATION 1F NPC 4$"

JubilifeCity_TVStation_1F_Text_NPC5:
	.string "TV STATION 1F NPC 5$"

JubilifeCity_TVStation_1F_Text_NPC6:
	.string "TV STATION 1F NPC 6$"

JubilifeCity_TVStation_1F_EventScript_NPC7::
	msgbox JubilifeCity_TVStation_1F_Text_NPC7, MSGBOX_NPC
	end

JubilifeCity_TVStation_1F_Text_NPC7:
	.string "TV STATION 1F NPC 7$"
