OreburghCity_BottomRightCondo_1F_MapScripts::
	.byte 0

OreburghCity_BottomRightCondo_1F_EventScript_NPC1::
	msgbox OreburghCity_BottomRightCondo_1F_Text_NPC1, MSGBOX_NPC
	end

OreburghCity_BottomRightCondo_1F_EventScript_NPC2::
	msgbox OreburghCity_BottomRightCondo_1F_Text_NPC2, MSGBOX_NPC
	end

OreburghCity_BottomRightCondo_1F_EventScript_NPC3::
	msgbox OreburghCity_BottomRightCondo_1F_Text_NPC3, MSGBOX_NPC
	end

OreburghCity_BottomRightCondo_1F_Text_NPC1:
	.string "BOTTOM RIGHT CONDO 1F\nNPC 1$"

OreburghCity_BottomRightCondo_1F_Text_NPC2:
	.string "BOTTOM RIGHT CONDO 1F\nNPC 2$"

OreburghCity_BottomRightCondo_1F_Text_NPC3:
	.string "BOTTOM RIGHT CONDO 1F\nNPC 3$"
