JubilifeCity_BattleDomeLobby_MapScripts::
	.byte 0

JubilifeCity_BattleDomeLobby_EventScript_NPC1::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_NPC2::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_NPC3::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_NPC4::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_NPC5::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC5, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_NPC6::
	msgbox JubilifeCity_BattleDomeLobby_Text_NPC6, MSGBOX_NPC
	end

JubilifeCity_BattleDomeLobby_EventScript_Sign1::
	msgbox JubilifeCity_BattleDomeLobby_Text_Sign1, MSGBOX_SIGN
	end

JubilifeCity_BattleDomeLobby_EventScript_Sign2::
	msgbox JubilifeCity_BattleDomeLobby_Text_Sign2, MSGBOX_SIGN
	end

JubilifeCity_BattleDomeLobby_EventScript_Sign3::
	msgbox JubilifeCity_BattleDomeLobby_Text_Sign3, MSGBOX_SIGN
	end

JubilifeCity_BattleDomeLobby_EventScript_Sign4::
	msgbox JubilifeCity_BattleDomeLobby_Text_Sign4, MSGBOX_SIGN
	end

JubilifeCity_BattleDomeLobby_Text_NPC1:
	.string "BATTLE DOME LOBBY NPC 1$"

JubilifeCity_BattleDomeLobby_Text_NPC2:
	.string "BATTLE DOME LOBBY NPC 2$"

JubilifeCity_BattleDomeLobby_Text_NPC3:
	.string "BATTLE DOME LOBBY NPC 3$"

JubilifeCity_BattleDomeLobby_Text_NPC4:
	.string "BATTLE DOME LOBBY NPC 4$"

JubilifeCity_BattleDomeLobby_Text_NPC5:
	.string "BATTLE DOME LOBBY NPC 5$"

JubilifeCity_BattleDomeLobby_Text_NPC6:
	.string "BATTLE DOME LOBBY NPC 6$"

JubilifeCity_BattleDomeLobby_Text_Sign1:
	.string "BATTLE DOME LOBBY SIGN 1$"

JubilifeCity_BattleDomeLobby_Text_Sign2:
	.string "BATTLE DOME LOBBY SIGN 2$"

JubilifeCity_BattleDomeLobby_Text_Sign3:
	.string "BATTLE DOME LOBBY SIGN 3$"

JubilifeCity_BattleDomeLobby_Text_Sign4:
	.string "BATTLE DOME LOBBY SIGN 4$"
