JubilifeCity_DexNavCompany_2F_MapScripts::
	.byte 0

JubilifeCity_DexNavCompany_2F_EventScript_NPC1::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_EventScript_NPC2::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_EventScript_NPC3::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_EventScript_NPC4::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_EventScript_NPC5::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC5, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_EventScript_NPC6::
	msgbox JubilifeCity_DexNavCompany_2F_Text_NPC6, MSGBOX_NPC
	end

JubilifeCity_DexNavCompany_2F_Text_NPC1:
	.string "DEX NAV COMPANY 2F NPC 1$"

JubilifeCity_DexNavCompany_2F_Text_NPC2:
	.string "DEX NAV COMPANY 2F NPC 2$"

JubilifeCity_DexNavCompany_2F_Text_NPC3:
	.string "DEX NAV COMPANY 2F NPC 3$"

JubilifeCity_DexNavCompany_2F_Text_NPC4:
	.string "DEX NAV COMPANY 2F NPC 4$"

JubilifeCity_DexNavCompany_2F_Text_NPC5:
	.string "DEX NAV COMPANY 2F NPC 5$"

JubilifeCity_DexNavCompany_2F_Text_NPC6:
	.string "DEX NAV COMPANY 2F NPC 6$"
