JubilifeCity_Condominium_2F_MapScripts::
	.byte 0

JubilifeCity_Condominium_2F_EventScript_NPC1::
	msgbox JubilifeCity_Condominium_2F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_Condominium_2F_EventScript_NPC2::
	msgbox JubilifeCity_Condominium_2F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_Condominium_2F_EventScript_NPC3::
	msgbox JubilifeCity_Condominium_2F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_Condominium_2F_Text_NPC1:
	.string "CONDOMINIUM 2F NPC 1$"

JubilifeCity_Condominium_2F_Text_NPC2:
	.string "CONDOMINIUM 2F NPC 2$"

JubilifeCity_Condominium_2F_Text_NPC3:
	.string "CONDOMINIUM 2F NPC 3$"
