JubilifeCity_TVStation_2F_MapScripts::
	.byte 0

JubilifeCity_TVStation_2F_EventScript_NPC1::
	msgbox JubilifeCity_TVStation_2F_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_TVStation_2F_Text_NPC1:
	.string "TV STATION 2F NPC 1$"

JubilifeCity_TVStation_2F_EventScript_NPC2::
	msgbox JubilifeCity_TVStation_2F_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_TVStation_2F_EventScript_NPC3::
	msgbox JubilifeCity_TVStation_2F_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_TVStation_2F_EventScript_NPC4::
	msgbox JubilifeCity_TVStation_2F_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_TVStation_2F_Text_NPC2:
	.string "TV STATION 2F NPC 2$"

JubilifeCity_TVStation_2F_Text_NPC3:
	.string "TV STATION 2F NPC 3$"

JubilifeCity_TVStation_2F_Text_NPC4:
	.string "TV STATION 2F NPC 4$"
