SandgemTown_BottomLeftHouse_1F_MapScripts::
	.byte 0

SandgemTown_BottomLeftHouse_1F_EventScript_NPC1::
	msgbox SandgemTown_BottomLeftHouse_1F_Text_NPC1, MSGBOX_NPC
	end

SandgemTown_BottomLeftHouse_1F_EventScript_NPC2::
	msgbox SandgemTown_BottomLeftHouse_1F_Text_NPC2, MSGBOX_NPC
	end

SandgemTown_BottomLeftHouse_1F_Text_NPC1:
	.string "Pokémon grow steadily stronger from\n"
	.string "battling against other Pokémon.\p"
	.string "At first, you should heal your Pokémon\n"
	.string "regularly at Poké Centers while you're\l"
	.string "leveling them up.$"

SandgemTown_BottomLeftHouse_1F_Text_NPC2:
	.string "A good Trainer is one that takes care\n"
	.string "not to let their Pokémon faint from\l"
	.string "losing HP.$"
