SandgemTown_BottomLeftHouse_1F_MapScripts::
	.byte 0

SandgemTown_BottomLeftHouse_1F_EventScript_NPC1::
	msgbox SandgemTown_BottomLeftHouse_1F_Text_NPC1, MSGBOX_NPC
	end

SandgemTown_BottomLeftHouse_1F_EventScript_NPC2::
	msgbox SandgemTown_BottomLeftHouse_1F_Text_NPC2, MSGBOX_NPC
	end

SandgemTown_BottomLeftHouse_1F_Text_NPC1:
	.string "BOTTOM LEFT HOUSE 1F NPC 1$"

SandgemTown_BottomLeftHouse_1F_Text_NPC2:
	.string "BOTTOM LEFT HOUSE 1F NPC 2$"
