
	.section .rodata
	.global DrumTbl3
	.align	2

DrumTbl3:

@**************** Voice 000 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 001 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 002 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 003 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 004 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 005 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 006 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 007 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 008 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 009 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 010 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 011 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 012 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 013 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 014 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 015 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 016 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 017 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 018 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 019 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 020 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 021 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 022 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 023 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 024 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 025 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 026 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 027 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 028 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 029 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 030 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 031 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 032 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 033 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 034 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 035 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 036 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	snd_16_Key_36_37
	.byte	255, 0, 255, 127

@**************** Voice 037 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	snd_16_Key_36_37
	.byte	255, 0, 255, 127

@**************** Voice 038 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	snd_16_Key_38
	.byte	255, 0, 255, 127

@**************** Voice 039 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 040 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 041 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 042 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 043 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 044 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 045 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 046 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 047 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 048 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 049 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 050 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 051 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 052 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 053 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 054 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 055 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 056 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 057 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 058 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 059 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 060 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 061 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 062 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 063 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 064 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 065 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 066 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 067 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 068 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 069 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 070 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 071 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 072 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 073 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 074 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 075 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 076 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 077 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 078 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 079 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 080 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 081 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 082 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 083 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 084 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 085 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 086 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 087 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 088 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 089 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 090 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 091 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 092 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 093 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 094 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 095 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 096 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 097 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 098 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 099 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 100 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 101 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 102 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 103 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 104 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 105 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 106 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 107 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 108 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 109 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 110 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 111 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 112 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 113 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 114 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 115 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 116 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 117 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 118 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 119 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 120 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 121 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 122 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 123 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 124 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 125 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 126 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 127 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0



