
	.section .rodata
	.global DrumTbl1
	.align	2

DrumTbl1:

@**************** Voice 000 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 001 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 002 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 003 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 004 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 005 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 006 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 007 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 008 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 009 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 010 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 011 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 012 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 013 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 014 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 015 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 016 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 017 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 018 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 019 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 020 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 021 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 022 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 023 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 024 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 025 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 026 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 027 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 028 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-4
	.word	snd_1_Key_28
	.byte	255, 0, 255, 165

@**************** Voice 029 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+4
	.word	snd_1_Key_29
	.byte	255, 0, 255, 165

@**************** Voice 030 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+12
	.word	snd_1_Key_30
	.byte	255, 0, 255, 165

@**************** Voice 031 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+22
	.word	snd_1_Key_31
	.byte	4, 0, 255, 165

@**************** Voice 032 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-19
	.word	snd_1_Key_32
	.byte	255, 0, 255, 165

@**************** Voice 033 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+2
	.word	snd_1_Key_33
	.byte	255, 0, 255, 242

@**************** Voice 034 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_34
	.byte	255, 0, 255, 165

@**************** Voice 035 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-4
	.word	snd_1_Key_35
	.byte	255, 0, 255, 242

@**************** Voice 036 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+2
	.word	snd_1_Key_36
	.byte	255, 0, 255, 242

@**************** Voice 037 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-19
	.word	snd_1_Key_37
	.byte	255, 230, 0, 230

@**************** Voice 038 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-16
	.word	snd_1_Key_38
	.byte	255, 0, 255, 242

@**************** Voice 039 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+21
	.word	snd_1_Key_39
	.byte	255, 0, 255, 165

@**************** Voice 040 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+15
	.word	snd_1_Key_40
	.byte	255, 240, 0, 154

@**************** Voice 041 ****************@

	.byte	DirectSound
	.byte	48
	.byte	0x0
	.byte	c_v-32
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 042 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-19
	.word	snd_1_Key_42
	.byte	255, 0, 255, 188

@**************** Voice 043 ****************@

	.byte	DirectSound
	.byte	53
	.byte	0x0
	.byte	c_v-16
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 044 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+37
	.word	snd_1_Key_44
	.byte	255, 0, 255, 188

@**************** Voice 045 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+0
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 046 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+20
	.word	snd_1_Key_46
	.byte	255, 242, 0, 212

@**************** Voice 047 ****************@

	.byte	DirectSound
	.byte	66
	.byte	0x0
	.byte	c_v+16
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 048 ****************@

	.byte	DirectSound
	.byte	72
	.byte	0x0
	.byte	c_v+32
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 049 ****************@

	.byte	DirectSound
	.byte	57
	.byte	0x0
	.byte	c_v-24
	.word	snd_1_Key_49
	.byte	255, 245, 0, 216

@**************** Voice 050 ****************@

	.byte	DirectSound
	.byte	74
	.byte	0x0
	.byte	c_v+48
	.word	snd_1_Key_41
	.byte	255, 0, 255, 127

@**************** Voice 051 ****************@

	.byte	DirectSound
	.byte	58
	.byte	0x0
	.byte	c_v-8
	.word	snd_1_Key_51
	.byte	255, 242, 0, 165

@**************** Voice 052 ****************@

	.byte	DirectSound
	.byte	59
	.byte	0x0
	.byte	c_v-47
	.word	snd_1_Key_52
	.byte	255, 246, 0, 216

@**************** Voice 053 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+15
	.word	snd_1_Key_53
	.byte	255, 246, 0, 165

@**************** Voice 054 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+6
	.word	snd_1_Key_54
	.byte	255, 0, 255, 165

@**************** Voice 055 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-10
	.word	snd_1_Key_55
	.byte	255, 231, 0, 216

@**************** Voice 056 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+49
	.word	snd_1_Key_56
	.byte	255, 0, 255, 165

@**************** Voice 057 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+24
	.word	snd_1_Key_57
	.byte	255, 246, 0, 216

@**************** Voice 058 ****************@

	.byte	DirectSound
	.byte	61
	.byte	0x0
	.byte	c_v-24
	.word	snd_1_Key_57
	.byte	255, 240, 0, 216

@**************** Voice 059 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+56
	.word	snd_1_Key_59
	.byte	255, 243, 0, 165

@**************** Voice 060 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-26
	.word	snd_1_Key_60
	.byte	255, 0, 255, 165

@**************** Voice 061 ****************@

	.byte	DirectSound
	.byte	57
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_60
	.byte	255, 0, 255, 165

@**************** Voice 062 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_62
	.byte	255, 0, 255, 165

@**************** Voice 063 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-4
	.word	snd_1_Key_63
	.byte	255, 0, 255, 165

@**************** Voice 064 ****************@

	.byte	DirectSound
	.byte	57
	.byte	0x0
	.byte	c_v+6
	.word	snd_1_Key_63
	.byte	255, 0, 255, 165

@**************** Voice 065 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+19
	.word	snd_1_Key_65
	.byte	255, 0, 255, 165

@**************** Voice 066 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_65
	.byte	255, 0, 255, 165

@**************** Voice 067 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-34
	.word	snd_1_Key_67
	.byte	255, 0, 255, 165

@**************** Voice 068 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+29
	.word	snd_1_Key_62
	.byte	255, 0, 255, 165

@**************** Voice 069 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-61
	.word	snd_1_Key_63
	.byte	255, 0, 255, 165

@**************** Voice 070 ****************@

	.byte	DirectSound
	.byte	63
	.byte	0x0
	.byte	c_v+13
	.word	snd_1_Key_63
	.byte	255, 0, 255, 165

@**************** Voice 071 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+0
	.word	snd_1_Key_71
	.byte	255, 0, 255, 165

@**************** Voice 072 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+26
	.word	snd_1_Key_72
	.byte	255, 0, 255, 165

@**************** Voice 073 ****************@

	.byte	DirectSound
	.byte	57
	.byte	0x0
	.byte	c_v+6
	.word	snd_1_Key_72
	.byte	255, 0, 255, 165

@**************** Voice 074 ****************@

	.byte	DirectSound
	.byte	55
	.byte	0x0
	.byte	c_v+0
	.word	snd_1_Key_72
	.byte	255, 0, 255, 165

@**************** Voice 075 ****************@

	.byte	DirectSound
	.byte	52
	.byte	0x0
	.byte	c_v-6
	.word	snd_1_Key_72
	.byte	255, 0, 255, 165

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	59
	.byte	0x0
	.byte	c_v-24
	.word	snd_1_Key_76
	.byte	255, 0, 255, 165

@**************** Voice 077 ****************@

	.byte	DirectSound
	.byte	56
	.byte	0x0
	.byte	c_v-8
	.word	snd_1_Key_76
	.byte	255, 0, 255, 165

@**************** Voice 078 ****************@

	.byte	DirectSound
	.byte	54
	.byte	0x0
	.byte	c_v+8
	.word	snd_1_Key_76
	.byte	255, 0, 255, 165

@**************** Voice 079 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+24
	.word	snd_1_Key_76
	.byte	255, 0, 255, 165

@**************** Voice 080 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+48
	.word	snd_1_Key_80
	.byte	255, 230, 0, 165

@**************** Voice 081 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-48
	.word	snd_1_Key_80
	.byte	255, 230, 0, 165

@**************** Voice 082 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_82
	.byte	255, 0, 255, 165

@**************** Voice 083 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v+26
	.word	snd_1_Key_83
	.byte	255, 0, 255, 165

@**************** Voice 084 ****************@

	.byte	DirectSound
	.byte	70
	.byte	0x0
	.byte	c_v+16
	.word	snd_1_Key_65
	.byte	255, 0, 255, 165

@**************** Voice 085 ****************@

	.byte	DirectSound
	.byte	54
	.byte	0x0
	.byte	c_v-16
	.word	snd_1_Key_65
	.byte	255, 0, 255, 165

@**************** Voice 086 ****************@

	.byte	DirectSound
	.byte	65
	.byte	0x0
	.byte	c_v-32
	.word	snd_1_Key_65
	.byte	255, 0, 255, 165

@**************** Voice 087 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-14
	.word	snd_1_Key_87
	.byte	255, 0, 255, 165

@**************** Voice 088 ****************@

	.byte	DirectSound
	.byte	60
	.byte	0x0
	.byte	c_v-44
	.word	snd_1_Key_88
	.byte	255, 243, 0, 165

@**************** Voice 089 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 090 ****************@

	.byte	ProgNoise
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	FineNoise
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 091 ****************@

	.byte	ProgNoise
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	FineNoise
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 092 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 093 ****************@

	.byte	ProgNoise
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	FineNoise
	.byte	0x0, 0x0, 0x0, 0x0

@**************** Voice 094 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 095 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 096 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 097 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 098 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 099 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 100 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 101 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 102 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 103 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 104 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 105 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 106 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 107 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 108 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 109 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 110 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 111 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 112 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 113 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 114 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 115 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 116 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 117 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 118 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 119 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 120 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 121 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 122 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 123 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 124 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 125 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 126 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0

@**************** Voice 127 ****************@

	.byte	0
	.byte	60
	.byte	0x0
	.byte	0x0
	.word	0
	.byte	0x0, 0x0, 0xF, 0x0



