JubilifeCity_TrainerSchool_MapScripts::
	.byte 0

JubilifeCity_TrainerSchool_EventScript_NPC1::
	msgbox JubilifeCity_TrainerSchool_Text_NPC1, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC2::
	msgbox JubilifeCity_TrainerSchool_Text_NPC2, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC3::
	msgbox JubilifeCity_TrainerSchool_Text_NPC3, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC4::
	msgbox JubilifeCity_TrainerSchool_Text_NPC4, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC5::
	msgbox JubilifeCity_TrainerSchool_Text_NPC5, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC6::
	msgbox JubilifeCity_TrainerSchool_Text_NPC6, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_NPC7::
	msgbox JubilifeCity_TrainerSchool_Text_NPC7, MSGBOX_NPC
	end

JubilifeCity_TrainerSchool_EventScript_Sign1::
	msgbox JubilifeCity_TrainerSchool_Text_Sign1, MSGBOX_SIGN
	end

JubilifeCity_TrainerSchool_EventScript_Sign2::
	msgbox JubilifeCity_TrainerSchool_Text_Sign2, MSGBOX_SIGN
	end

JubilifeCity_TrainerSchool_EventScript_Sign3::
	msgbox JubilifeCity_TrainerSchool_Text_Sign3, MSGBOX_SIGN
	end

JubilifeCity_TrainerSchool_EventScript_Sign4::
	msgbox JubilifeCity_TrainerSchool_Text_Sign4, MSGBOX_SIGN
	end

JubilifeCity_TrainerSchool_EventScript_Sign5::
	msgbox JubilifeCity_TrainerSchool_Text_Sign5, MSGBOX_SIGN
	end

JubilifeCity_TrainerSchool_Text_NPC1:
	.string "TRAINER SCHOOL NPC 1$"

JubilifeCity_TrainerSchool_Text_NPC2:
	.string "TRAINER SCHOOL NPC 2$"

JubilifeCity_TrainerSchool_Text_NPC3:
	.string "TRAINER SCHOOL NPC 3$"

JubilifeCity_TrainerSchool_Text_NPC4:
	.string "TRAINER SCHOOL NPC 4$"

JubilifeCity_TrainerSchool_Text_NPC5:
	.string "TRAINER SCHOOL NPC 5$"

JubilifeCity_TrainerSchool_Text_NPC6:
	.string "TRAINER SCHOOL NPC 6$"

JubilifeCity_TrainerSchool_Text_NPC7:
	.string "TRAINER SCHOOL NPC 7$"

JubilifeCity_TrainerSchool_Text_Sign1:
	.string "TRAINER SCHOOL SIGN 1$"

JubilifeCity_TrainerSchool_Text_Sign2:
	.string "TRAINER SCHOOL SIGN 2$"

JubilifeCity_TrainerSchool_Text_Sign3:
	.string "TRAINER SCHOOL SIGN 3$"

JubilifeCity_TrainerSchool_Text_Sign4:
	.string "TRAINER SCHOOL SIGN 4$"

JubilifeCity_TrainerSchool_Text_Sign5:
	.string "TRAINER SCHOOL SIGN 5$"
